[package]
name = "mylib"
version = "0.1.0"
authors = ["Jeff Hodges <jmhodges@signal.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.15.0"

[lib]
crate_type = ["cdylib"]
